### PR TITLE
Practice github flow for lou

### PR DESCRIPTION
**Pull request by loupendley**
# Here are some  RANDOM comments
# fixed the bugs in this file

@SoidaPalacios check this out

### CODE REVIEW

**Comment by loupendley** [comment]
If you haven't already commented, please do so comment on #10 
How cool! kind of like Wiki cross referencing.

**Comment by SoidaPalacios** [comment]
Hi Lou!

**Comment by SoidaPalacios** [comment]
#100

**Comment by SoidaPalacios** [comment]
I closed prematurely... reopening.

**Pull request merged**
