### PR TITLE
Vpop's demo for GitHub flow, starting locally as well

### PR DESCRIPTION
**Pull request by vp186006**
## This is a Demo Header
- [x] Understand git via a demo
- [x] Awesome, start a pull request
- [x] Code review changes before commit

:+1:  What do you think :question: @atagakch

### CODE REVIEW

**Comment by atagakch** [comment]
problem in the SEG code. check again

**Comment by vp186006** [comment]
let's talk to RD and fix the SEG issue.

**Comment by vp186006** [comment]
Am done with the merge

**Comment by atagakch** [comment]
same

**Pull request merged**
