### PR TITLE
Practice github flow from beg to end

### PR DESCRIPTION
**Pull request by githubteacher**
This PR aims to demonstrate the end-to-end workflow.
### TODO
- [x] demo cross-references
- [x] demo fix/close/resolve

@brianamarie am I forgetting anything?

### CODE REVIEW

**Comment by brianamarie** [comment]
Looks good @githubteacher 👍  :shipit:

**Comment by githubteacher** [comment]
If you haven't already, please be sure to comment on #10!

**Comment by justinjosecjj** [comment]
.

**Comment by apoorva89** [comment]
@githubteacher Thanks for the class :+1:

**Pull request merged**
