### PR TITLE
adding crumbs!

### PR DESCRIPTION
**Pull request by dt186001**
[Aw Yiss](http://youtu.be/oHg5SJYRHA0)

### CODE REVIEW

**Comment by andrewpett** [comment]
mf bread crumbs

**Comment by andrewpett** [comment]
mansoor_head

**Comment by kevin-brewer** [comment]
mbjt

**Comment by andrewpett** [comment]
http://i.imgur.com/skSfvX2.gif

**Comment by andrewpett** [comment]
[http://i.imgur.com/skSfvX2.gif](url)

**Comment by ra186026** [comment]
dtung

**Comment by DanielDwyer** [comment]
You guys seem fun!

**Comment by andrewpett** [comment]
spock-butan

**Comment by andrewpett** [comment]
oh boy. animated GIFs work. this can only lead to very bad things

**Comment by kevin-brewer** [comment]
It can lead.... TO ADVENTURE

giphy

**Comment by ra186026** [comment]
slowclapnickcage

**Pull request merged**
