### PR TITLE
My edits of the demo

### PR DESCRIPTION
**Pull request by tcbyrd**
## Heading! :8ball:
- [ ] :headphones: 

cc @osowskit @sbarnekow

### CODE REVIEW

**Comment by osowskit** [comment]
💣  found SSH keys created by GitHub Desktop don't automatically register w/ the command-line.  happy merging!!

**Comment by sbarnekow** [comment]
Sup dude 👋

**Comment by tcbyrd** [comment]
@osowskit I don't even see how to generate keys in GH Desktop.  Of course that could be a Windows/Mac diff.

**Comment by osowskit** [comment]
I've found it does it behind the scenes and moves it to a location custom location - which is both good and bad.

**Comment by tcbyrd** [comment]
Closing to resolve conflicts

**Pull request closed without merging**
