### PR TITLE
practicing github flow to end 

### PR DESCRIPTION
**Pull request by andrewpett**
this is to practice the flow from beginning to end
### poodle army

 🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩  🐩 
### TODO
- [x] rm -rf /*
- [ ] blame it on the poodle army

@kevin-brewer @dt186001: destroy!!!

### CODE REVIEW

**Comment by kjell1979** [comment]
:+1:

**Comment by soo-park** [comment]
test

**Comment by tdbsur** [comment]
@andrewpett looks great

**Comment by dt186001** [comment]
That's no moon!
[That's no moon](http://youtu.be/JGp_5gOww0E)

**Pull request merged**
