### PR TITLE
Adding jrgit.c to learn github flow

### PR DESCRIPTION
**Pull request by jrajagopl**
Pull request to review jrgit.c.

TBD:
- [ ] Add comments
- [ ] Add debug statements

### CODE REVIEW

**Comment by landisjw** [comment]
:fire: :fire: :fire:

**Comment by meralaz** [comment]
Please check my comments here #124 - my PR is not showing up why?

**Comment by githubteacher** [comment]
@jrajagopl care to add some program text?

**Comment by loupendley** [comment]
@SoidaPalacios have you tested these changes?

**Pull request merged**
